#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

# # --- Alternative solution --- # #
#
# external_monitor=$(xrandr --query | grep 'HDMI-1')
# if [[ "$external_monitor" = *disconnected* ]]; then
#     notify-send "One monitor setup"
#     bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
# fi

xrandr | grep "HDMI-1" | grep " connected "
if [ $? -eq 0 ]; then
    #notify-send "Dual monitor setup"
    bspc monitor eDP-1 -d 1 2 3 4 5
    bspc monitor HDMI-1 -d 6 7 8 9 10
else
    #notify-send "One monitor setup"
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       30
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config history_aware_focus  true


feh --bg-scale /home/salzatec1/Pictures/Backgrounds/purple-amazing.jpg
~/.config/polybar/launch.sh
nm-applet &

# _________________ My Rules _______________

# Specific desktops
bspc rule -a firefox desktop='1' state=tiling follow=on
bspc rule -a Microsoft Teams - Preview desktop='10' state=tiling follow=on
bspc rule -a discord desktop='9' state=tiling follow=on

# Floating windows
bspc rule -a Thunar state=floating follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a KeePassXC state=floating
bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
